In [ ]:
#load the necessary libraries
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input
from keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array
import numpy as np
import tensorflow as tf
from keras import callbacks
from keras import optimizers
from keras.engine import Model
from keras.layers import Dropout, Flatten, Dense
from keras.optimizers import Adam
from keras.applications import VGG16
from keras.datasets import cifar10
from keras.utils import to_categorical
from tensorflow.keras.preprocessing import timeseries_dataset_from_array
from keras.models import Sequential

In [ ]:
train_datagen = ImageDataGenerator(rescale=1./255)
X_train = train_datagen.flow_from_directory(
        '...TIROCINIO/train_ok4',
        target_size=(150,150),
        #batch_size=32,
        shuffle=False,
        class_mode="categorical"
    )

Found 1032 images belonging to 7 classes.


In [ ]:
train_datagen = ImageDataGenerator(rescale=1./255)
X_test = train_datagen.flow_from_directory(
        '...TIROCINIO/test_ok4',
        target_size=(150,150),
        #batch_size=32,
        shuffle=False,
        class_mode="categorical"
    )

Found 260 images belonging to 7 classes.


In [ ]:
w=X_test.labels
c = np.zeros((w.size, w.max()+1))
c[np.arange(w.size),w] = 1
c

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
c.shape

(260, 7)

In [ ]:
ctest=c.reshape(65,4,7)
ctest.shape

(65, 4, 7)

In [ ]:
v=X_train.labels

In [ ]:

b = np.zeros((v.size, v.max()+1))
b[np.arange(v.size),v] = 1
b

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
b.shape

(1032, 7)

In [ ]:
btrain=b.reshape(258,4,7)
btrain

array([[[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       [[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       [[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.]],

       [[0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.]],

       [[0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.]]])

In [ ]:
ct= np.load('...TIROCINIO/classipredette_4frame/classesTest4f.npy')
ct.argmax(axis=-1)

array([0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 5, 0, 0, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1,
       0, 3, 5, 1, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3,
       3, 3, 4, 4, 4, 4, 0, 4, 4, 4, 0, 4, 4, 4, 2, 4, 4, 2, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 6, 3, 3, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 2, 2, 2, 5, 5, 2, 2,
       0, 0, 0, 0, 4, 0, 4, 0, 0, 0, 0, 0, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 2, 4, 4, 4,
       6, 6, 6, 6, 6, 6, 6, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 1, 1, 1, 5, 6, 6, 6])

In [ ]:
ctr=np.load('...TIROCINIO/classipredette_4frame/classesTrain4f.npy')
ctr.argmax(axis=-1)

array([0, 0, 0, ..., 6, 6, 6])

In [ ]:
print(ct.shape)
print(ctr.shape)

(260, 7)
(1032, 7)


In [ ]:
x= ctr.reshape(258,4,7)
#train_set

In [ ]:
y=ct.reshape(65,4,7)
#test_set

In [ ]:

x.shape

(258, 4, 7)

In [ ]:
y.shape


(65, 4, 7)

In [ ]:
btrain.shape
print(btrain[:,0,:].shape)

btrain = btrain[:,0,:]

(258, 7)


In [ ]:
ctest.shape
print(ctest[:,0,:].shape)

ctest = ctest[:,0,:]

(65, 7)


In [ ]:
ctest.shape

(65, 7)

In [ ]:
from keras.layers import LSTM
n_timesteps=4
n_features=7
n_outputs=7
model = Sequential()

#model.add(Dropout(0.5))
#model.add(LSTM(100))
model.add(LSTM(50, input_shape=( n_timesteps,n_features),  return_sequences=True))
#model.add(Dropout(0.5))
model.add(Flatten())
#model.add(Dense(100, activation='relu'))
model.add(Dense(7, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


In [ ]:
model.summary()

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_13 (LSTM)               (None, 4, 50)             11600     
_________________________________________________________________
flatten_13 (Flatten)         (None, 200)               0         
_________________________________________________________________
dense_21 (Dense)             (None, 7)                 1407      
Total params: 13,007
Trainable params: 13,007
Non-trainable params: 0
_________________________________________________________________


In [ ]:
train=tf.keras.utils.to_categorical(x.argmax(axis=-1), num_classes=7)

In [ ]:
train.shape

(258, 4, 7)

In [ ]:
test=tf.keras.utils.to_categorical(y.argmax(axis=-1), num_classes=7)

In [ ]:
test.shape

(65, 4, 7)

In [ ]:
ctest.shape

(65, 7)

In [ ]:
model.fit(train, btrain, validation_data=(test, ctest), epochs=16)

Epoch 1/16
9/9 [==============================] - 0s 32ms/step - loss: 0.3254 - accuracy: 0.9225 - val_loss: 1.2203 - val_accuracy: 0.6462
Epoch 2/16
9/9 [==============================] - 0s 23ms/step - loss: 0.3133 - accuracy: 0.9225 - val_loss: 1.2877 - val_accuracy: 0.6462
Epoch 3/16
9/9 [==============================] - 0s 24ms/step - loss: 0.3087 - accuracy: 0.9225 - val_loss: 1.2858 - val_accuracy: 0.6462
Epoch 4/16
9/9 [==============================] - 0s 20ms/step - loss: 0.3074 - accuracy: 0.9264 - val_loss: 1.2350 - val_accuracy: 0.6462
Epoch 5/16
9/9 [==============================] - 0s 22ms/step - loss: 0.3345 - accuracy: 0.9225 - val_loss: 1.2392 - val_accuracy: 0.6462
Epoch 6/16
9/9 [==============================] - 0s 18ms/step - loss: 0.3201 - accuracy: 0.9225 - val_loss: 1.2734 - val_accuracy: 0.6462
Epoch 7/16
9/9 [==============================] - 0s 18ms/step - loss: 0.3029 - accuracy: 0.9186 - val_loss: 1.3255 - val_accuracy: 0.6462
Epoch 8/16
9/9 [===========

In [ ]:
from keras.layers import LSTM
n_timesteps=4
n_features=7
n_outputs=7
model = Sequential()

#model.add(Dropout(0.5))
#model.add(LSTM(100))
model.add(LSTM(100, input_shape=( n_timesteps,n_features),  return_sequences=True))
#model.add(Dropout(0.5))
model.add(Flatten())
#model.add(Dense(100, activation='relu'))
model.add(Dense(7, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(train, btrain, validation_data=(test, ctest), epochs=10)

Epoch 1/10
9/9 [==============================] - 3s 147ms/step - loss: 1.8833 - accuracy: 0.5446 - val_loss: 1.8058 - val_accuracy: 0.6615
Epoch 2/10
9/9 [==============================] - 0s 13ms/step - loss: 1.7052 - accuracy: 0.9285 - val_loss: 1.6817 - val_accuracy: 0.6769
Epoch 3/10
9/9 [==============================] - 0s 12ms/step - loss: 1.5227 - accuracy: 0.9231 - val_loss: 1.5315 - val_accuracy: 0.6923
Epoch 4/10
9/9 [==============================] - 0s 13ms/step - loss: 1.3035 - accuracy: 0.9065 - val_loss: 1.3511 - val_accuracy: 0.6923
Epoch 5/10
9/9 [==============================] - 0s 12ms/step - loss: 1.0477 - accuracy: 0.9242 - val_loss: 1.1883 - val_accuracy: 0.6923
Epoch 6/10
9/9 [==============================] - 0s 14ms/step - loss: 0.7968 - accuracy: 0.9226 - val_loss: 1.1046 - val_accuracy: 0.6923
Epoch 7/10
9/9 [==============================] - 0s 12ms/step - loss: 0.6380 - accuracy: 0.8989 - val_loss: 1.0900 - val_accuracy: 0.6769
Epoch 8/10
9/9 [==========

In [ ]:
from keras.layers import LSTM
n_timesteps=4
n_features=7
n_outputs=7
model = Sequential()

#model.add(Dropout(0.5))
#model.add(LSTM(100))
model.add(LSTM(200, input_shape=( n_timesteps,n_features),  return_sequences=True))
#model.add(Dropout(0.5))
model.add(Flatten())
#model.add(Dense(100, activation='relu'))
model.add(Dense(7, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(train, btrain, validation_data=(test, ctest), epochs=10)

Epoch 1/10
9/9 [==============================] - 3s 86ms/step - loss: 1.8744 - accuracy: 0.6038 - val_loss: 1.7534 - val_accuracy: 0.6923
Epoch 2/10
9/9 [==============================] - 0s 18ms/step - loss: 1.5975 - accuracy: 0.8983 - val_loss: 1.5435 - val_accuracy: 0.6923
Epoch 3/10
9/9 [==============================] - 0s 20ms/step - loss: 1.2837 - accuracy: 0.8985 - val_loss: 1.3092 - val_accuracy: 0.6923
Epoch 4/10
9/9 [==============================] - 0s 18ms/step - loss: 0.8430 - accuracy: 0.9256 - val_loss: 1.2058 - val_accuracy: 0.6923
Epoch 5/10
9/9 [==============================] - 0s 19ms/step - loss: 0.6030 - accuracy: 0.9038 - val_loss: 1.2447 - val_accuracy: 0.6769
Epoch 6/10
9/9 [==============================] - 0s 21ms/step - loss: 0.4799 - accuracy: 0.9058 - val_loss: 1.2729 - val_accuracy: 0.6615
Epoch 7/10
9/9 [==============================] - 0s 18ms/step - loss: 0.3833 - accuracy: 0.9193 - val_loss: 1.2496 - val_accuracy: 0.6615
Epoch 8/10
9/9 [===========

In [ ]:
model.evaluate(train,btrain)

pred= model.predict_classes(train)

true = np.argmax(btrain,axis=-1)
from sklearn import metrics
metrics.accuracy_score(true,pred)

print(true)
print(pred)

#controlla quali leement sbaglia

In [ ]:
import numpy as np
from sklearn.metrics import confusion_matrix,classification_report


predictions = model.predict(train)
predictions = np.argmax(predictions, axis= 1)
predictions.shape

(258,)

In [ ]:
import numpy as np
from sklearn.metrics import confusion_matrix,classification_report

class_labels = list(X_train.class_indices.keys())   
print(class_labels)
v=X_train.labels
b = np.zeros((v.size, v.max()+1))
b[np.arange(v.size),v] = 1
btrain=b.reshape(258,4,7)
btrain = btrain[:,0,:]
btrain = np.argmax(btrain, axis=-1)
predictions = model.predict(train)
predictions = np.argmax(predictions, axis= -1)
#predictions.shape

print(confusion_matrix(btrain, predictions,  labels=None, sample_weight=None, normalize=None))
print()

report = classification_report(btrain, predictions, target_names=class_labels)
print(report)

['1_anger', '2_contempt', '3_disgust', '4_fear', '5_happy', '6_sadness', '7_surprise']
[[35  0  2  0  0  0  0]
 [ 2  9  0  0  1  1  0]
 [ 1  0 44  0  2  1  0]
 [ 0  0  1 14  3  0  0]
 [ 0  0  1  0 54  0  0]
 [ 3  0  0  0  1 18  0]
 [ 0  0  3  0  0  0 62]]

              precision    recall  f1-score   support

     1_anger       0.85      0.95      0.90        37
  2_contempt       1.00      0.69      0.82        13
   3_disgust       0.86      0.92      0.89        48
      4_fear       1.00      0.78      0.88        18
     5_happy       0.89      0.98      0.93        55
   6_sadness       0.90      0.82      0.86        22
  7_surprise       1.00      0.95      0.98        65

    accuracy                           0.91       258
   macro avg       0.93      0.87      0.89       258
weighted avg       0.92      0.91      0.91       258



In [ ]:
import numpy as np
from sklearn.metrics import confusion_matrix,classification_report

class_labels = list(X_test.class_indices.keys())   
print(class_labels)
w=X_test.labels
c = np.zeros((w.size, w.max()+1))
c[np.arange(w.size),w] = 1
ctest=c.reshape(65,4,7)
ctest = ctest[:,0,:]
ctest = np.argmax(ctest, axis=-1)
predictionstest = model.predict(test)
predictionstest = np.argmax(predictionstest, axis= -1)
#predictions.shape

#Confusion matrix whose i-th row and j-th column entry indicates 
#the number of samples with true label being i-th class and predicted label being j-th class.
print(confusion_matrix(ctest, predictionstest,  labels=None, sample_weight=None, normalize=None))
print()

report = classification_report(ctest, predictionstest, target_names=class_labels)
print(report)

['1_anger', '2_contempt', '3_disgust', '4_fear', '5_happy', '6_sadness', '7_surprise']
[[ 7  0  1  0  0  0  0]
 [ 2  1  0  0  2  0  0]
 [ 1  0 10  0  0  0  0]
 [ 0  0  0  1  5  0  0]
 [ 0  0  0  0 11  0  1]
 [ 2  0  2  0  1  0  1]
 [ 0  1  0  1  1  0 14]]

              precision    recall  f1-score   support

     1_anger       0.58      0.88      0.70         8
  2_contempt       0.50      0.20      0.29         5
   3_disgust       0.77      0.91      0.83        11
      4_fear       0.50      0.17      0.25         6
     5_happy       0.55      0.92      0.69        12
   6_sadness       0.00      0.00      0.00         6
  7_surprise       0.88      0.82      0.85        17

    accuracy                           0.68        65
   macro avg       0.54      0.56      0.52        65
weighted avg       0.62      0.68      0.62        65



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
